coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 78%
        threshold: 1%
    patch:
      default:
        target: 78%

ignore:
  - "src/test/**"
  - "**/Main.java"

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false
