coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 87%
        threshold: 1%
    patch:
      default:
        target: 87%

ignore:
  - "src/test/**"

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false
