import numpy as np
import matplotlib.pyplot as plt
import os
import style_utils

style_utils.apply_style()

DATA_DIR = "datasets/dct/"

def read_data(filename):
    with open(filename, 'r') as f:
        return np.array([float(line.strip()) for line in f])

def plot_idct_comparison():
    """
    Plot IDCT comparison.
    Shows the original signal vs the reconstructed signal (using Java IDCT).
    """
    
    # Load data
    original = read_data(os.path.join(DATA_DIR, "dct_basic_input.txt"))
    # Load Java output (generated by IDCTTest)
    java_recon_file = os.path.join(DATA_DIR, "dct_basic_idct_java.txt")
    
    if not os.path.exists(java_recon_file):
        print(f"Java output file not found: {java_recon_file}")
        return

    java_recon = read_data(java_recon_file)
    
    # Create figure
    fig, axes = plt.subplots(3, 1, figsize=(10, 10))
    
    t = np.arange(len(original))
    
    # Plot 1: Original Signal
    axes[0].plot(t, original, 'o-', label='Original Signal', linewidth=2, markersize=6)
    axes[0].set_title('Original Signal')
    axes[0].set_ylabel('Amplitude')
    axes[0].grid(True, alpha=0.3)
    axes[0].legend()
    
    # Plot 2: Reconstructed Signal (Java IDCT)
    axes[1].plot(t, java_recon, 'x--', label='Reconstructed (Java IDCT)', linewidth=2, markersize=8, color='orange')
    axes[1].set_title('Reconstructed via IDCT')
    axes[1].set_ylabel('Amplitude')
    axes[1].grid(True, alpha=0.3)
    axes[1].legend()

    # Plot 3: Error
    diff = original - java_recon
    rmse = np.sqrt(np.mean(diff**2))
    axes[2].plot(t, diff, 'r.-', label=f'Reconstruction Error (RMSE={rmse:.2e})')
    style_utils.finalize_diff_plot(axes[2], original)
    axes[2].set_title('Difference (Original - Reconstructed)')
    axes[2].set_xlabel('Sample Index')
    axes[2].set_ylabel('Error')
    axes[2].legend()
    
    plt.suptitle('IDCT Reconstruction Verification', fontsize=14)
    plt.tight_layout()
    
    os.makedirs('python/figs/dct', exist_ok=True)
    style_utils.save_plot(fig, "dct/idct_comparison.png")
    plt.close(fig)

if __name__ == "__main__":
    plot_idct_comparison()
    print("IDCT comparison plot generated.")
