package com.hissain.jscipy.math;

import com.hissain.jscipy.TestMetrics;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class InterpolationTest {

    private final Interpolation interpolation = new Interpolation();

    private static final double TOLERANCE = 0.001;

    @Test
    public void testLinearInterpolationData1() throws IOException {
        double[] x = readData("datasets/interpolation/interpolation_input_x_1.txt");
        double[] y = readData("datasets/interpolation/interpolation_input_y_1.txt");
        double[] newX = readData("datasets/interpolation/interpolation_input_new_x_1.txt");
        double[] expectedY = readData("datasets/interpolation/interpolation_output_linear_1.txt");

        double[] actualY = interpolation.linear(x, y, newX);

        try (java.io.PrintWriter writer = new java.io.PrintWriter(
                "datasets/interpolation/interpolation_output_linear_java_1.txt")) {
            for (double v : actualY) {
                writer.println(v);
            }
        }

        double rmse = calculateRMSE(expectedY, actualY);

        System.out.println("RMSE for Linear Interpolation 1: " + rmse);
        TestMetrics.log("Math", "Interpolation Linear (Test 1)", rmse);
        assertTrue(rmse < TOLERANCE, "RMSE too high: " + rmse);
        assertArrayEquals(expectedY, actualY, TOLERANCE);
    }

    @Test
    public void testLinearInterpolationData2() throws IOException {
        double[] x = readData("datasets/interpolation/interpolation_input_x_2.txt");
        double[] y = readData("datasets/interpolation/interpolation_input_y_2.txt");
        double[] newX = readData("datasets/interpolation/interpolation_input_new_x_2.txt");
        double[] expectedY = readData("datasets/interpolation/interpolation_output_linear_2.txt");

        double[] actualY = interpolation.linear(x, y, newX);

        try (java.io.PrintWriter writer = new java.io.PrintWriter(
                "datasets/interpolation/interpolation_output_linear_java_2.txt")) {
            for (double v : actualY) {
                writer.println(v);
            }
        }

        double rmse = calculateRMSE(expectedY, actualY);

        System.out.println("RMSE for Linear Interpolation 2: " + rmse);
        TestMetrics.log("Math", "Interpolation Linear (Test 2)", rmse);
        assertTrue(rmse < TOLERANCE, "RMSE too high: " + rmse);
        assertArrayEquals(expectedY, actualY, TOLERANCE);
    }

    @Test
    public void testCubicInterpolationData1() throws IOException {
        double[] x = readData("datasets/interpolation/interpolation_input_x_1.txt");
        double[] y = readData("datasets/interpolation/interpolation_input_y_1.txt");
        double[] newX = readData("datasets/interpolation/interpolation_input_new_x_1.txt");
        double[] expectedY = readData("datasets/interpolation/interpolation_output_cubic_1.txt");

        double[] actualY = interpolation.cubic(x, y, newX);

        try (java.io.PrintWriter writer = new java.io.PrintWriter(
                "datasets/interpolation/interpolation_output_cubic_java_1.txt")) {
            for (double v : actualY) {
                writer.println(v);
            }
        }

        double rmse = calculateRMSE(expectedY, actualY);

        System.out.println("RMSE for Cubic Interpolation 1: " + rmse);
        TestMetrics.log("Math", "Interpolation Cubic (Test 1)", rmse);
        assertTrue(rmse < TOLERANCE, "RMSE too high: " + rmse);
        assertArrayEquals(expectedY, actualY, TOLERANCE);
    }

    @Test
    public void testCubicInterpolationData2() throws IOException {
        double[] x = readData("datasets/interpolation/interpolation_input_x_2.txt");
        double[] y = readData("datasets/interpolation/interpolation_input_y_2.txt");
        double[] newX = readData("datasets/interpolation/interpolation_input_new_x_2.txt");
        double[] expectedY = readData("datasets/interpolation/interpolation_output_cubic_2.txt");

        double[] actualY = interpolation.cubic(x, y, newX);

        try (java.io.PrintWriter writer = new java.io.PrintWriter(
                "datasets/interpolation/interpolation_output_cubic_java_2.txt")) {
            for (double v : actualY) {
                writer.println(v);
            }
        }

        double rmse = calculateRMSE(expectedY, actualY);

        System.out.println("RMSE for Cubic Interpolation 2: " + rmse);
        TestMetrics.log("Math", "Interpolation Cubic (Test 2)", rmse);
        assertTrue(rmse < TOLERANCE, "RMSE too high: " + rmse);
        assertArrayEquals(expectedY, actualY, TOLERANCE);
    }

    @Test
    public void testQuadraticSplineInterpolatesKnots() throws IOException {
        // Test 1 Data (Generated by updated generate_interpolation_test_data.py)
        // We use the same input x/y as linear/cubic tests

        double[] x = readData("datasets/interpolation/interpolation_input_x_1.txt");
        double[] y = readData("datasets/interpolation/interpolation_input_y_1.txt");

        // Evaluate at the knots themselves
        double[] actualY = interpolation.quadratic(x, y, x);

        // Should match y exactly (within double precision)
        // Using large tolerance for safety, but theoretically should be very small
        assertArrayEquals(y, actualY, 1e-10, "Spline must pass through control points");
    }

    @Test
    public void testQuadraticSplineSimpleParabola() {
        // y = x^2
        double[] x = new double[] { 0, 1, 2, 3, 4, 5 };
        double[] y = new double[x.length];
        for (int i = 0; i < x.length; i++)
            y[i] = x[i] * x[i];

        // Evaluate at midpoints
        double[] newX = new double[] { 0.5, 1.5, 2.5 };
        double[] expectedY = new double[] { 0.25, 2.25, 6.25 }; // x^2 values

        double[] actualY = interpolation.quadratic(x, y, newX);

        // Assert basic approximation
        assertArrayEquals(expectedY, actualY, 0.5, "Parabola approx check");
    }

    @Test
    public void testQuadraticSplineMatchSciPy() throws IOException {
        double[] x = readData("datasets/interpolation/interpolation_input_x_1.txt");
        double[] y = readData("datasets/interpolation/interpolation_input_y_1.txt");
        double[] newX = readData("datasets/interpolation/interpolation_input_new_x_1.txt");
        double[] expectedY = readData("datasets/interpolation/interpolation_output_quadratic_1.txt");

        double[] actualY = interpolation.quadratic(x, y, newX);

        // Save output for plotting
        try (java.io.PrintWriter writer = new java.io.PrintWriter(
                "datasets/interpolation/interpolation_output_quadratic_java_1.txt")) {
            for (double v : actualY) {
                writer.println(v);
            }
        }

        double rmse = calculateRMSE(expectedY, actualY);
        System.out.println("MEASURED RMSE Against SciPy (Test 1): " + rmse);
        TestMetrics.log("Math", "Interpolation Quadratic (Test 1)", rmse);

        // Test 2
        double[] x2 = readData("datasets/interpolation/interpolation_input_x_2.txt");
        double[] y2 = readData("datasets/interpolation/interpolation_input_y_2.txt");
        double[] newX2 = readData("datasets/interpolation/interpolation_input_new_x_2.txt");
        double[] expectedY2 = readData("datasets/interpolation/interpolation_output_quadratic_2.txt");

        double[] actualY2 = interpolation.quadratic(x2, y2, newX2);

        // Save output for plotting
        try (java.io.PrintWriter writer = new java.io.PrintWriter(
                "datasets/interpolation/interpolation_output_quadratic_java_2.txt")) {
            for (double v : actualY2) {
                writer.println(v);
            }
        }

        double rmse2 = calculateRMSE(expectedY2, actualY2);
        System.out.println("MEASURED RMSE Against SciPy (Test 2): " + rmse2);
        TestMetrics.log("Math", "Interpolation Quadratic (Test 2)", rmse2);

        // Assert strict compliance
        assertTrue(rmse < 1e-12, "Test 1 RMSE too high");
        assertTrue(rmse2 < 1e-12, "Test 2 RMSE too high");
    }

    private double[] readData(String filePath) throws IOException {
        return Files.lines(Paths.get(filePath))
                .mapToDouble(Double::parseDouble)
                .toArray();
    }

    private double calculateRMSE(double[] expected, double[] actual) {
        double sumSquareError = 0;
        for (int i = 0; i < expected.length; i++) {
            sumSquareError += Math.pow(expected[i] - actual[i], 2);
        }
        return Math.sqrt(sumSquareError / expected.length);
    }
}
